# This is a basic workflow to help you get started with Actions

name: Build lingmo-installer amd64

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: docker.io/library/debian:trixie-slim

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Update repository
        run: apt-get update -y
      - name: Upgrade packages
        run: apt-get upgrade -y
      - name: Install the basic dev packages
        run: apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++
      # Runs a single command using the runners shell
      - name: Run a build script
        run: |
          mk-build-deps -i -t "apt-get -y" -r  > /dev/null
          dpkg-buildpackage -b -uc -us -tc -j$(nproc)
          mv ../*.deb ./

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: |
            ./*.deb
            !./*dbg*
          if-no-files-found: error